### ISSUE TITLE
Yelp - User can see search field section of website

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/recreate-website#1]
## 🖼️ Wireframe

<img width="1426" alt="Screen Shot 2021-06-03 at 1 58 13 PM" src="https://user-images.githubusercontent.com/76749207/120711038-bf9db900-c473-11eb-88b7-aa305529f7cb.png">

## ✅ Task List

- [x] Create div for field/section
- [x] Add image as background for section/row of website
- [x] Create shade over background image
- [x] Create 3 div elements for top nav bar, search filed and logo, and photo source
- [x] Top section
  - [x] Create 2 divs for left and right anchor tags of row
  - [x] Create 3 anchor tags for review, events, and talk
  - [x] Create 2 anchor tags for login and sign up
- [ ] Search section
  - [x] Create div and add yelp logo
  - [x] Create div and add 2 input fields and search anchor/icon
  - [x] Add 5 icons / anchor tags for plumber, restaurant, home services, delivery, etc.
- [x] Photo source section
  - [x] Create div and add photo label and photographer 
- [x] Style to wireframe
- [x] Test on private browser
- [x] Fix all errors
